version: '3.1'

services:
  directus:
    image: directus/directus:9.0.0-rc.99
    restart: always
    networks:
      - reverse-proxy
      - directus-network
    ports:
      - 8055:8055
    environment:
      - KEY=abcd
      - SECRET=abcd
      - DB_CLIENT=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=directus
      - DB_USER=root
      - DB_PASSWORD=root
      - ADMIN_EMAIL=user@domain.local
      - ADMIN_PASSWORD=root
      - PUBLIC_URL=http://domain.local
    depends_on:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.services.DIRECTUS.loadbalancer.server.port=8055
      - traefik.http.routers.DIRECTUS.rule=Host(`domain.local`)
      - traefik.http.routers.DIRECTUS.entrypoints=http
  database:
    image: mariadb
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - directus-network
    environment:
      - MYSQL_DATABASE=directus
      - MYSQL_ROOT_PASSWORD=root
  reverseproxy:
    image: traefik:v2.5.3
    restart: always
    networks:
      - reverse-proxy
    volumes:
      - ./conf/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080

networks:
  reverse-proxy:
  directus-network: