[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false
    network = reverse-proxy

[api]
  dashboard = true
  debug = true
  insecure = true

 [entryPoints]
  [entryPoints.http]
    address = ":80"
